termMappings:
  https://lschema.org/attributeName: ls:attributeName
  https://lschema.org/attributeIndex: ls:attributeIndex
  https://lschema.org/attributeValue: ls:attributeValue
  https://lschema.org/entityId: ls:entityId
  https://lschema.org/entityIdFields: ls:entityIdFields
  https://lschema.org/nodeId: ls:nodeId
  https://lschema.org/schemaNodeId: ls:schemaNodeId
  https://lschema.org/edgeLabel: ls:edgeLabel
  https://lschema.org/DocumentNode: ls:documentNode
  https://lschema.org/entitySchema: ls:entitySchema
  https://lschema.org/xml/ns: ls:xml/ns
  https://lschema.org/conditional: ls:conditional
  https://lschema.org/floatTest: ls:floatTest
  https://lschema.org/boolTest: ls:boolTest
  extension: extension
  high: high
  low: low
  root: root

# low, high json:number
propertyTypes:
  https://lschema.org/attributeIndex: Integer
  https://lschema.org/floatTest: Float
  https://lschema.org/negationInd: Boolean
  https://lschema.org/inversionInd: Boolean
  https://lschema.org/someDate: Date, YYYY-MM-DD
  https://lschema.org/someDateTime: DateTime, YYYY-MM-DD HH:mm:ss
  https://lschema.org/someInteger: Integer
  https://lschema.org/someFloat: Float
  https://lschema.org/someBoolean: Boolean

namespaceMappings:
  https://lschema.org/: ls
  https://lschema.org/A/: lsa
  https://lschema.org/Y/: lsy