termMappings:
  https://lschema.org/AttributeName: ls:attributeName
  https://lschema.org/AttributeValue: ls:attributeValue
  https://lschema.org/EntityID: ls:entityId
  https://lschema.org/NodeID: ls:nodeId
  https://lschema.org/SchemaNodeID: ls:schemaNodeId
  https://lschema.org/EdgeLabel: ls:edgeLabel

termExpansion:
  ls:attributeName: https://lschema.org/AttributeName
  ls:attributeValue: https://lschema.org/AttributeValue
  ls:entityId: https://lschema.org/EntityID
  ls:nodeId: https://lschema.org/NodeID
  ls:schemaNodeId: https://lschema.org/SchemaNodeID
  ls:edgeLabel: https://lschema.org/EdgeLabel

namespaceMappings:
  https://lschema.org/: ls
  https://lschema.org/Y: ls:Y
  https://lschema.org/vs: lsv
  https://lschema.org/vs/X: lsv:X
    